version: '3'

services:
  api-proxy:
    build:
      context: ./api-proxy
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
  front-end:
    build:
      context: ./front-end
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    links:
      - "api-proxy"
